# Generated by Django 6.0.3 on 2026-07-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCleaningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('missing', 'Handle Missing Values'), ('outlier', 'Outlier Detection'), ('format', 'Format Validation'), ('duplicate', 'Duplicate Detection')], max_length=50)),
                ('condition', models.TextField(help_text='JSON condition logic')),
                ('action', models.CharField(choices=[('fill_mean', 'Fill with Mean'), ('fill_median', 'Fill with Median'), ('fill_mode', 'Fill with Mode'), ('drop', 'Drop Record'), ('flag', 'Flag for Review'), ('transform', 'Apply Transformation')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_field', models.CharField(max_length=100)),
                ('transform_type', models.CharField(choices=[('log', 'Log Transform'), ('sqrt', 'Square Root'), ('scale', 'Min-Max Scale'), ('standardize', 'Z-Score Standardize'), ('onehot', 'One-Hot Encode'), ('binning', 'Binning/Categorization'), ('interaction', 'Feature Interaction')], max_length=50)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('output_field', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
