# Generated by Django 6.0.3 on 2026-06-01 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureEncoderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('feature_type', models.CharField(max_length=50)),
                ('encoding_method', models.CharField(max_length=50)),
                ('categories', models.JSONField(default=list, null=True)),
                ('fitted_params', models.JSONField(default=dict, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreprocessingJob',
            fields=[
                ('job_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('who_api', 'WHO Global API'), ('moh_db', 'MOH Kenya Database'), ('patient_form', 'Patient Input Form'), ('geolocation', 'Geolocation Layer')], max_length=20)),
                ('raw_record_count', models.PositiveIntegerField(default=0)),
                ('processed_record_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Preprocessing parameters')),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deduplication_completed', models.DateTimeField(blank=True, null=True)),
                ('imputation_completed', models.DateTimeField(blank=True, null=True)),
                ('encoding_completed', models.DateTimeField(blank=True, null=True)),
                ('smote_completed', models.DateTimeField(blank=True, null=True)),
                ('anonymisation_completed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('symptoms', models.JSONField(default=dict, help_text='32 binary symptom features')),
                ('risk_behaviours', models.JSONField(default=dict)),
                ('demographics', models.JSONField(default=dict)),
                ('geographic_region', models.CharField(max_length=50)),
                ('prior_sti_history', models.JSONField(default=list)),
                ('composite_risk_score', models.FloatField(null=True)),
                ('temporal_features', models.JSONField(default=dict)),
                ('sti_labels', models.JSONField(default=dict, help_text='One-hot encoded STI classes')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20, null=True)),
                ('differential_privacy_applied', models.BooleanField(default=False)),
                ('k_anonymity_group', models.PositiveIntegerField(help_text='k-anonymity group ID', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='preprocessing.preprocessingjob')),
            ],
            options={
                'indexes': [models.Index(fields=['geographic_region', 'risk_level'], name='preprocessi_geograp_bdb9ae_idx'), models.Index(fields=['anonymous_id'], name='preprocessi_anonymo_bf8087_idx')],
            },
        ),
    ]
