# Generated by Django 6.0.3 on 2026-06-01 09:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutbreakNotificationConfig',
            fields=[
                ('config_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sti_type', models.CharField(max_length=20)),
                ('county', models.CharField(blank=True, max_length=50)),
                ('threshold_type', models.CharField(choices=[('incidence_rate', 'Incidence Rate per 100k'), ('case_count', 'Absolute Case Count'), ('percentage_increase', 'Week-over-Week % Increase'), ('forecast_exceedance', 'Forecast Exceedance')], max_length=20)),
                ('threshold_value', models.FloatField()),
                ('notify_moh', models.BooleanField(default=True)),
                ('notify_who', models.BooleanField(default=False)),
                ('notify_county_officers', models.BooleanField(default=True)),
                ('email_recipients', models.JSONField(default=list)),
                ('sms_recipients', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WHODataExport',
            fields=[
                ('export_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('pdf', 'PDF'), ('xlsx', 'Excel'), ('hl7', 'HL7 FHIR')], max_length=10)),
                ('data_period_start', models.DateField()),
                ('data_period_end', models.DateField()),
                ('record_count', models.PositiveIntegerField()),
                ('counties_covered', models.JSONField(default=list)),
                ('sti_types_included', models.JSONField(default=list)),
                ('who_country_code', models.CharField(default='KEN', max_length=10)),
                ('who_reporting_period', models.CharField(max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size_bytes', models.PositiveIntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('transmitted_to_who', models.BooleanField(default=False)),
                ('transmitted_at', models.DateTimeField(blank=True, null=True)),
                ('transmission_confirmation', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GridCell',
            fields=[
                ('cell_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('county', models.CharField(db_index=True, max_length=50)),
                ('sub_county', models.CharField(blank=True, max_length=50)),
                ('population_estimate', models.PositiveIntegerField(default=1)),
            ],
            options={
                'unique_together': {('county', 'sub_county')},
            },
        ),
        migrations.CreateModel(
            name='OutbreakAlertHistory',
            fields=[
                ('alert_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sti_type', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=50)),
                ('actual_value', models.FloatField()),
                ('threshold_value', models.FloatField()),
                ('notifications_sent', models.JSONField(default=list)),
                ('notification_timestamp', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100)),
                ('response_actions', models.JSONField(default=list)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('trigger_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moh_reporting.outbreaknotificationconfig')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyDashboardMetric',
            fields=[
                ('metric_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('burden', 'STI Burden'), ('coverage', 'Testing Coverage'), ('treatment', 'Treatment Uptake'), ('forecast', 'Forecast'), ('inequity', 'Health Inequity')], max_length=50)),
                ('indicator_name', models.CharField(max_length=100)),
                ('county', models.CharField(blank=True, db_index=True, max_length=50)),
                ('sub_county', models.CharField(blank=True, max_length=50)),
                ('current_value', models.FloatField()),
                ('previous_value', models.FloatField(null=True)),
                ('target_value', models.FloatField(null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('trend_direction', models.CharField(choices=[('improving', 'Improving'), ('worsening', 'Worsening'), ('stable', 'Stable'), ('insufficient_data', 'Insufficient Data')], max_length=20)),
                ('trend_percentage', models.FloatField(null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('data_quality_score', models.FloatField(default=1.0)),
                ('data_source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('category', 'indicator_name', 'county', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='SurveillanceReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('weekly', 'Weekly Summary'), ('monthly', 'Monthly Burden Estimate'), ('outbreak', 'Outbreak Alert'), ('annual', 'Annual Review'), ('ad_hoc', 'Ad-hoc Request')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('scope_national', models.BooleanField(default=True)),
                ('counties_included', models.JSONField(default=list)),
                ('total_assessments', models.PositiveIntegerField(default=0)),
                ('total_confirmed_cases', models.PositiveIntegerField(default=0)),
                ('sti_breakdown', models.JSONField(default=dict, help_text='Counts per STI type')),
                ('risk_distribution', models.JSONField(default=dict)),
                ('age_distribution', models.JSONField(default=dict)),
                ('sex_distribution', models.JSONField(default=dict)),
                ('geographic_distribution', models.JSONField(default=dict)),
                ('tests_conducted', models.PositiveIntegerField(default=0)),
                ('tests_positive', models.PositiveIntegerField(default=0)),
                ('treatment_initiated', models.PositiveIntegerField(default=0)),
                ('treatment_completed', models.PositiveIntegerField(default=0)),
                ('testing_coverage_rate', models.FloatField(default=0.0)),
                ('untested_high_risk_estimate', models.PositiveIntegerField(default=0)),
                ('facility_gaps', models.JSONField(default=list)),
                ('who_indicator_codes', models.JSONField(default=list)),
                ('who_submission_ready', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready for Download'), ('sent', 'Sent to Recipient'), ('failed', 'Generation Failed')], default='generating', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('pdf', 'PDF'), ('xlsx', 'Excel'), ('hl7', 'HL7 FHIR')], default='csv', max_length=10)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('sent_to_who', models.BooleanField(default=False)),
                ('sent_to_moh', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type', 'period_end'], name='moh_reporti_report__22ff02_idx'), models.Index(fields=['scope_national', 'generated_at'], name='moh_reporti_scope_n_9fb80a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AggregatedIncident',
            fields=[
                ('incident_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sti_type', models.CharField(db_index=True, max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('incident_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grid_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='moh_reporting.gridcell')),
            ],
            options={
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['sti_type', 'period_end'], name='moh_reporti_sti_typ_59cbe3_idx'), models.Index(fields=['period_start', 'period_end'], name='moh_reporti_period__24c1dd_idx')],
            },
        ),
    ]
