# Generated by Django 6.0.3 on 2026-07-13 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('weekly', 'Weekly Summary'), ('monthly', 'Monthly Report'), ('quarterly', 'Quarterly Report'), ('annual', 'Annual Report'), ('custom', 'Custom Report'), ('outbreak', 'Outbreak Alert')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('query_config', models.JSONField(default=dict, help_text='JSON configuration for data queries')),
                ('output_formats', models.JSONField(default=list, help_text="['pdf', 'excel', 'csv', 'json']")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('county_filter', models.CharField(blank=True, max_length=100)),
                ('facility_filter', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('total_screenings', models.PositiveIntegerField(default=0)),
                ('total_positive', models.PositiveIntegerField(default=0)),
                ('total_high_risk', models.PositiveIntegerField(default=0)),
                ('generated_by', models.CharField(blank=True, max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moh_reporting.reporttemplate')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
