# Generated by Django 6.0.3 on 2026-06-01 09:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotAlert',
            fields=[
                ('alert_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('sti_type', models.CharField(choices=[('hiv', 'HIV'), ('chlamydia', 'Chlamydia'), ('syphilis', 'Syphilis'), ('gonorrhoea', 'Gonorrhoea'), ('hpv', 'HPV'), ('hsv2', 'HSV-2'), ('all', 'All STIs Combined')], max_length=20)),
                ('primary_county', models.CharField(max_length=50)),
                ('affected_sub_counties', models.JSONField(default=list)),
                ('cluster_size_cells', models.PositiveIntegerField()),
                ('total_incidents', models.PositiveIntegerField()),
                ('population_at_risk', models.PositiveIntegerField()),
                ('detection_period_start', models.DateField()),
                ('detection_period_end', models.DateField()),
                ('forecast_30_day', models.FloatField(null=True)),
                ('forecast_60_day', models.FloatField(null=True)),
                ('forecast_90_day', models.FloatField(null=True)),
                ('year_over_year_delta', models.FloatField(help_text='Percentage change vs same period last year', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('geojson_heatmap', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GridCell',
            fields=[
                ('cell_id', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False)),
                ('grid_lat', models.FloatField()),
                ('grid_lon', models.FloatField()),
                ('county', models.CharField(db_index=True, max_length=50)),
                ('sub_county', models.CharField(db_index=True, max_length=50)),
                ('centroid_lat', models.FloatField(blank=True, null=True)),
                ('centroid_lon', models.FloatField(blank=True, null=True)),
                ('boundary', models.JSONField(blank=True, null=True)),
                ('population_estimate', models.PositiveIntegerField(default=0)),
                ('healthcare_access_index', models.FloatField(default=0.0)),
                ('road_network_score', models.FloatField(default=0.0)),
                ('morans_i', models.FloatField(help_text='Spatial autocorrelation index', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['county', 'sub_county'], name='geospatial__county_24972b_idx'), models.Index(fields=['grid_lat', 'grid_lon'], name='geospatial__grid_la_7f1f63_idx'), models.Index(fields=['centroid_lat', 'centroid_lon'], name='geospatial__centroi_8fb6e7_idx')],
                'unique_together': {('grid_lat', 'grid_lon')},
            },
        ),
        migrations.CreateModel(
            name='HealthcareFacility',
            fields=[
                ('facility_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('county', models.CharField(db_index=True, max_length=50)),
                ('sub_county', models.CharField(db_index=True, max_length=50)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('services', models.JSONField(default=list, help_text='List of STI testing services offered')),
                ('operating_hours', models.JSONField(default=dict)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_moh_registered', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('catchment_population', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lon'], name='geospatial__lat_a3fdff_idx'), models.Index(fields=['county', 'is_active'], name='geospatial__county_760171_idx')],
            },
        ),
        migrations.CreateModel(
            name='AggregatedIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sti_type', models.CharField(choices=[('hiv', 'HIV'), ('chlamydia', 'Chlamydia'), ('syphilis', 'Syphilis'), ('gonorrhoea', 'Gonorrhoea'), ('hpv', 'HPV'), ('hsv2', 'HSV-2'), ('all', 'All STIs Combined')], db_index=True, max_length=20)),
                ('incident_count', models.PositiveIntegerField(default=0)),
                ('unique_patients_estimate', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('risk_score', models.FloatField(default=0.0, help_text='Normalised risk score 0-1')),
                ('kde_density', models.FloatField(help_text='Kernel Density Estimation value', null=True)),
                ('cluster_id', models.IntegerField(help_text='DBSCAN cluster label', null=True)),
                ('is_outlier', models.BooleanField(default=False, help_text='DBSCAN noise point')),
                ('dp_noise_applied', models.BooleanField(default=True)),
                ('dp_epsilon', models.FloatField(default=0.1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grid_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='geospatial.gridcell')),
            ],
            options={
                'indexes': [models.Index(fields=['sti_type', 'period_start', 'period_end'], name='geospatial__sti_typ_3a8613_idx'), models.Index(fields=['risk_level', 'grid_cell'], name='geospatial__risk_le_14e3e5_idx'), models.Index(fields=['cluster_id'], name='geospatial__cluster_7ef666_idx')],
                'unique_together': {('grid_cell', 'sti_type', 'period_start')},
            },
        ),
    ]
