# Generated by Django 6.0.3 on 2026-07-13 19:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catchment_area', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('service_radius_km', models.FloatField(default=5.0)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo', to='clinicians.facility')),
            ],
        ),
        migrations.CreateModel(
            name='GeographicRiskZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('county', models.CharField(db_index=True, max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('risk_score', models.FloatField()),
                ('population_at_risk', models.PositiveIntegerField(default=0)),
                ('total_screenings', models.PositiveIntegerField(default=0)),
                ('positive_cases', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['county', 'risk_level'], name='geospatial__county_581a33_idx'), models.Index(fields=['period_start', 'period_end'], name='geospatial__period__7fd94a_idx')],
            },
        ),
    ]
