# Generated by Django 6.0.3 on 2026-06-01 09:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiasAuditReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(max_length=50)),
                ('model_type', models.CharField(choices=[('classifier', 'STI Risk Classifier'), ('forecaster', 'Outbreak Forecaster')], max_length=20)),
                ('subgroup_results', models.JSONField(default=dict, help_text='\n    {\n        "age_13_17": {"auc_roc": 0.87, "f1": 0.78, "sample_count": 450},\n        "age_18_24": {"auc_roc": 0.91, "f1": 0.84, "sample_count": 3200},\n        "age_25_34": {"auc_roc": 0.89, "f1": 0.81, "sample_count": 2800},\n        ...\n    }\n    ')),
                ('violations_found', models.JSONField(default=list, help_text='\n    [\n        {"subgroup": "age_65_plus", "metric": "auc_roc", "value": 0.78, "threshold": 0.80}\n    ]\n    ')),
                ('calibration_by_subgroup', models.JSONField(default=dict)),
                ('passes_bias_audit', models.BooleanField(default=True)),
                ('recommended_actions', models.JSONField(default=list)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('review_date', models.DateField(null=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=100, unique=True)),
                ('data_type', models.CharField(choices=[('patient_input', 'Patient Input Forms'), ('processed_record', 'Processed Anonymised Records'), ('audit_log', 'Audit Logs'), ('model_training_data', 'Model Training Data'), ('geospatial_grid', 'Geospatial Grid Data')], max_length=50)),
                ('retention_days', models.PositiveIntegerField()),
                ('auto_delete_enabled', models.BooleanField(default=True)),
                ('last_execution', models.DateTimeField(null=True)),
                ('records_deleted_last_run', models.PositiveIntegerField(default=0)),
                ('execution_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalValidationGate',
            fields=[
                ('gate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('patient_guidance', 'Patient Guidance'), ('clinician_guidance', 'Clinician Guidance'), ('treatment_protocol', 'Treatment Protocol'), ('differential_diagnosis', 'Differential Diagnosis')], max_length=30)),
                ('content_id', models.UUIDField()),
                ('stage_drafted', models.DateTimeField(auto_now_add=True)),
                ('stage_clinician_1_review', models.DateTimeField(null=True)),
                ('stage_clinician_2_review', models.DateTimeField(null=True)),
                ('stage_id_specialist_review', models.DateTimeField(null=True)),
                ('stage_moh_review', models.DateTimeField(null=True)),
                ('clinician_1_name', models.CharField(blank=True, max_length=100)),
                ('clinician_1_credentials', models.CharField(blank=True, max_length=200)),
                ('clinician_2_name', models.CharField(blank=True, max_length=100)),
                ('clinician_2_credentials', models.CharField(blank=True, max_length=200)),
                ('id_specialist_name', models.CharField(blank=True, max_length=100)),
                ('id_specialist_credentials', models.CharField(blank=True, max_length=200)),
                ('moh_signatory_name', models.CharField(blank=True, max_length=100)),
                ('moh_signatory_credentials', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_clinical_review', 'Under Clinical Review'), ('clinician_approved', 'Clinician Approved'), ('id_specialist_approved', 'ID Specialist Approved'), ('moh_approved', 'MOH Approved'), ('deployed', 'Deployed'), ('deprecated', 'Deprecated')], default='draft', max_length=30)),
                ('deployment_blocked', models.BooleanField(default=True)),
                ('block_reason', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('annual_review_due', models.DateField()),
                ('last_reviewed_at', models.DateTimeField(null=True)),
                ('previous_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.clinicalvalidationgate')),
            ],
            options={
                'ordering': ['-stage_drafted'],
            },
        ),
        migrations.CreateModel(
            name='DriftDetectionResult',
            fields=[
                ('detection_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_version', models.CharField(max_length=50)),
                ('feature_name', models.CharField(max_length=100)),
                ('psi_score', models.FloatField()),
                ('psi_threshold', models.FloatField(default=0.2)),
                ('is_drift_detected', models.BooleanField(default=False)),
                ('training_distribution', models.JSONField(default=dict)),
                ('current_distribution', models.JSONField(default=dict)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('retraining_triggered', models.BooleanField(default=False)),
                ('retraining_job_id', models.UUIDField(null=True)),
                ('alert_sent', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['model_version', 'feature_name'], name='compliance__model_v_8641e8_idx'), models.Index(fields=['is_drift_detected', 'severity'], name='compliance__is_drif_9af3d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImmutableAuditLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('prediction_made', 'Prediction Made'), ('guidance_accessed', 'Guidance Accessed'), ('guidance_approved', 'Guidance Approved'), ('guidance_deployed', 'Guidance Deployed'), ('threshold_override', 'Threshold Override'), ('alert_acknowledged', 'Alert Acknowledged'), ('alert_resolved', 'Alert Resolved'), ('patient_referred', 'Patient Referred'), ('test_ordered', 'Test Ordered'), ('model_deployed', 'Model Deployed'), ('model_retrained', 'Model Retrained'), ('drift_detected', 'Drift Detected'), ('bias_violation', 'Bias Violation Detected'), ('data_deleted', 'Data Deleted per Retention Policy'), ('compliance_review', 'Compliance Review Conducted')], max_length=30)),
                ('action_timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_type', models.CharField(choices=[('clinician', 'Clinician'), ('system', 'System'), ('admin', 'Administrator'), ('patient', 'Patient (Anonymous)')], max_length=20)),
                ('actor_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('actor_credentials', models.CharField(blank=True, max_length=200)),
                ('anonymous_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('risk_score', models.FloatField(null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('sti_probabilities', models.JSONField(default=dict)),
                ('guidance_version', models.PositiveIntegerField(null=True)),
                ('guidance_id', models.UUIDField(null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.UUIDField(null=True)),
                ('previous_log_hash', models.CharField(blank=True, max_length=64)),
                ('current_log_hash', models.CharField(max_length=64)),
                ('payload_summary', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-action_timestamp'],
                'indexes': [models.Index(fields=['anonymous_id', 'action_timestamp'], name='compliance__anonymo_e71290_idx'), models.Index(fields=['actor_id', 'action_type'], name='compliance__actor_i_538dd9_idx'), models.Index(fields=['action_type', 'action_timestamp'], name='compliance__action__6592c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceViolation',
            fields=[
                ('violation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('category', models.CharField(choices=[('privacy', 'Privacy Violation'), ('bias', 'Bias/Fairness Violation'), ('validation', 'Clinical Validation Failure'), ('data_retention', 'Data Retention Non-Compliance'), ('security', 'Security Incident'), ('audit_gap', 'Missing Audit Trail')], max_length=50)),
                ('description', models.TextField()),
                ('affected_system_component', models.CharField(max_length=100)),
                ('detected_by', models.CharField(max_length=100)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('remediation_plan', models.TextField(blank=True)),
                ('remediation_deadline', models.DateField()),
                ('remediation_completed', models.BooleanField(default=False)),
                ('remediation_completed_at', models.DateTimeField(null=True)),
                ('remediated_by', models.CharField(blank=True, max_length=100)),
                ('escalated_to', models.CharField(blank=True, max_length=100)),
                ('escalation_reason', models.TextField(blank=True)),
                ('related_audit_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.immutableauditlog')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
