# Generated by Django 6.0.3 on 2026-06-01 09:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('who_api', 'WHO Global Surveillance API'), ('moh_db', 'MOH Kenya HL7 FHIR Database'), ('geolocation', 'Geolocation / PostGIS Layer'), ('patient_form', 'Patient Input Form')], max_length=20, unique=True)),
                ('base_url', models.URLField(help_text='API or FHIR base URL for this source')),
                ('auth_method', models.CharField(choices=[('api_key', 'API Key + TLS'), ('oauth2', 'OAuth 2.0 + VPN'), ('internal', 'Internal / No Auth'), ('anon_tls', 'Anonymous ID + TLS')], default='api_key', max_length=20)),
                ('credential_env_key', models.CharField(blank=True, help_text='Name of the env var holding the API key or client secret', max_length=100)),
                ('sync_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('last_successful_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Source Configuration',
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('who_api', 'WHO Global Surveillance API'), ('moh_db', 'MOH Kenya HL7 FHIR Database'), ('geolocation', 'Geolocation / PostGIS Layer'), ('patient_form', 'Patient Input Form')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial — Some Records Failed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('triggered_by', models.CharField(choices=[('scheduler', 'Scheduler'), ('api', 'API Call'), ('manual', 'Manual')], default='scheduler', max_length=20)),
                ('raw_record_count', models.PositiveIntegerField(default=0)),
                ('accepted_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('forwarded_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_window_start', models.DateTimeField(blank=True, null=True)),
                ('sync_window_end', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True)),
                ('preprocessing_job_id', models.UUIDField(blank=True, help_text='UUID of the downstream PreprocessingJob this data was forwarded to', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'status'], name='data_ingest_source_fa8ff9_idx'), models.Index(fields=['created_at'], name='data_ingest_created_263a9d_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeoRecord',
            fields=[
                ('geo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude_grid', models.FloatField(help_text='Latitude rounded to ±5km grid')),
                ('longitude_grid', models.FloatField(help_text='Longitude rounded to ±5km grid')),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('sti_counts', models.JSONField(default=dict, help_text='Dict of STI type → case count within this grid cell')),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('suppressed', models.BooleanField(default=False, help_text='True if cell count < 100 and output is suppressed')),
                ('week_start', models.DateField(help_text='Monday of the reporting week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_records', to='data_ingestion.ingestionjob')),
            ],
            options={
                'indexes': [models.Index(fields=['county', 'week_start'], name='data_ingest_county_a6c01b_idx')],
                'unique_together': {('latitude_grid', 'longitude_grid', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('who_api', 'WHO Global Surveillance API'), ('moh_db', 'MOH Kenya HL7 FHIR Database'), ('geolocation', 'Geolocation / PostGIS Layer'), ('patient_form', 'Patient Input Form')], max_length=20)),
                ('status', models.CharField(choices=[('raw', 'Raw — Not Yet Forwarded'), ('forwarded', 'Forwarded to Preprocessing'), ('rejected', 'Rejected — Validation Failed'), ('duplicate', 'Duplicate — Skipped')], default='raw', max_length=20)),
                ('raw_payload', models.JSONField(help_text='Verbatim payload from source')),
                ('geographic_region', models.CharField(blank=True, max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('validation_errors', models.JSONField(default=list, help_text='List of field-level validation error messages')),
                ('is_duplicate', models.BooleanField(default=False)),
                ('duplicate_of', models.UUIDField(blank=True, help_text='record_id of the original record this duplicates', null=True)),
                ('forwarded_at', models.DateTimeField(blank=True, null=True)),
                ('preprocessing_record_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='data_ingestion.ingestionjob')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'status'], name='data_ingest_source_685929_idx'), models.Index(fields=['geographic_region'], name='data_ingest_geograp_678711_idx'), models.Index(fields=['record_date'], name='data_ingest_record__cd6311_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncAuditLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('who_api', 'WHO Global Surveillance API'), ('moh_db', 'MOH Kenya HL7 FHIR Database'), ('geolocation', 'Geolocation / PostGIS Layer'), ('patient_form', 'Patient Input Form')], max_length=20)),
                ('event_type', models.CharField(choices=[('job_started', 'Job Started'), ('job_completed', 'Job Completed'), ('job_failed', 'Job Failed'), ('record_accepted', 'Record Accepted'), ('record_rejected', 'Record Rejected'), ('record_duplicate', 'Record Duplicate'), ('record_forwarded', 'Record Forwarded to Preprocessing'), ('auth_success', 'Authentication Succeeded'), ('auth_failure', 'Authentication Failed'), ('rate_limit_hit', 'Rate Limit Hit'), ('conflict_resolved', 'Conflict Resolved')], max_length=40)),
                ('detail', models.JSONField(default=dict, help_text='Event-specific payload')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='data_ingestion.ingestionjob')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['source', 'event_type'], name='data_ingest_source_2200c2_idx'), models.Index(fields=['timestamp'], name='data_ingest_timesta_bdc1d2_idx')],
            },
        ),
    ]
