# Generated by Django 6.0.3 on 2026-06-01 09:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('model_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_type', models.CharField(choices=[('risk_classifier', 'STI Risk Classifier (XGBoost + RF)'), ('pattern_predictor', 'Pattern Predictor (LSTM + Prophet)'), ('hotspot_engine', 'Geospatial Hotspot Engine (DBSCAN + KDE)')], db_index=True, max_length=30)),
                ('version', models.CharField(help_text="Semantic version string, e.g. '1.0.0'", max_length=20)),
                ('mlflow_run_id', models.CharField(blank=True, help_text='MLflow run ID for experiment tracking cross-reference', max_length=100)),
                ('artefact_path', models.CharField(help_text='Path to serialised model artefact (joblib / .pt / Prophet JSON)', max_length=500)),
                ('feature_schema_version', models.CharField(default='1.0', help_text='Version of the feature engineering schema used at training time', max_length=20)),
                ('evaluation_metrics', models.JSONField(default=dict, help_text='AUC-ROC, F1, MAPE etc. per class/horizon at validation time')),
                ('meets_deployment_threshold', models.BooleanField(default=False, help_text='True when AUC-ROC ≥ 0.85 (classifier) or MAPE ≤ 15% (predictor)')),
                ('psi_score', models.FloatField(help_text='Population Stability Index computed weekly. >0.2 triggers retraining alert.', null=True)),
                ('last_psi_check', models.DateTimeField(blank=True, null=True)),
                ('drift_alert_active', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False, help_text='Only one model per type may be active at a time.')),
                ('clinical_validation_completed', models.BooleanField(default=False, help_text='Hard gate — model may not serve patient/clinician outputs until True.')),
                ('validated_by', models.CharField(blank=True, max_length=200)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_type', 'is_active'], name='ml_pipeline_model_t_05d32a_idx'), models.Index(fields=['drift_alert_active'], name='ml_pipeline_drift_a_ac8dcd_idx')],
                'unique_together': {('model_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='RiskPrediction',
            fields=[
                ('prediction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_id', models.CharField(db_index=True, max_length=64)),
                ('input_feature_hash', models.CharField(help_text='SHA-256 of the normalised feature vector for audit reproducibility', max_length=64)),
                ('input_features', models.JSONField(help_text='Full feature vector at inference time. Stored for SHAP audit trail.')),
                ('sti_probabilities', models.JSONField(help_text='Dict of {sti_class: probability_score} for all 7 classes')),
                ('predicted_class', models.CharField(choices=[('hiv', 'HIV'), ('chlamydia', 'Chlamydia'), ('syphilis', 'Syphilis'), ('gonorrhoea', 'Gonorrhoea'), ('hpv', 'HPV'), ('hsv2', 'HSV-2'), ('none', 'None / Indeterminate')], help_text='Highest-probability STI class', max_length=20)),
                ('overall_risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('overall_risk_score', models.FloatField(help_text='Max probability across all STI classes')),
                ('shap_values', models.JSONField(help_text='SHAP value dict for the top contributing features', null=True)),
                ('top_features', models.JSONField(default=list, help_text='Top 3 features driving this prediction [{feature, shap_value, direction}]')),
                ('confidence_lower', models.FloatField(help_text='95% CI lower bound', null=True)),
                ('confidence_upper', models.FloatField(help_text='95% CI upper bound', null=True)),
                ('clinical_review_required', models.BooleanField(default=False, help_text='True when any class probability ≥ 0.7. Hard block on patient display.')),
                ('clinical_review_completed', models.BooleanField(default=False)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_predictions', to='ml_pipeline.mlmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionAuditLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text="'prediction_created', 'clinical_review_completed', 'guidance_surfaced', 'model_activated', 'drift_alert'", max_length=50)),
                ('anonymous_id', models.CharField(blank=True, max_length=64)),
                ('actor', models.CharField(blank=True, help_text='System component or clinician identifier (anonymised)', max_length=100)),
                ('payload', models.JSONField(default=dict, help_text='Event-specific metadata. No PII stored.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml_pipeline.mlmodel')),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ml_pipeline.riskprediction')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_type', models.CharField(choices=[('risk_classifier', 'STI Risk Classifier (XGBoost + RF)'), ('pattern_predictor', 'Pattern Predictor (LSTM + Prophet)'), ('hotspot_engine', 'Geospatial Hotspot Engine (DBSCAN + KDE)')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('drift_triggered', 'Triggered by Drift Alert')], default='pending', max_length=20)),
                ('trigger', models.CharField(default='scheduled', help_text="'scheduled', 'drift_alert', 'manual', or 'data_update'", max_length=50)),
                ('training_data_start', models.DateField()),
                ('training_data_end', models.DateField()),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('class_distribution', models.JSONField(default=dict, help_text='Record count per STI class label before SMOTE')),
                ('hyperparameters', models.JSONField(default=dict)),
                ('error_log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resulting_model', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_job', to='ml_pipeline.mlmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriftReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('psi_score', models.FloatField(help_text='Overall Population Stability Index')),
                ('feature_psi', models.JSONField(default=dict, help_text='Per-feature PSI scores. Used to identify which inputs are drifting.')),
                ('alert_triggered', models.BooleanField(default=False)),
                ('subgroup_auc', models.JSONField(default=dict, help_text='AUC-ROC per demographic subgroup. <0.80 flags bias review.')),
                ('bias_flag', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_reports', to='ml_pipeline.mlmodel')),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('model_version', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='OutbreakForecast',
            fields=[
                ('forecast_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('county', models.CharField(db_index=True, max_length=50)),
                ('sti_type', models.CharField(choices=[('hiv', 'HIV'), ('chlamydia', 'Chlamydia'), ('syphilis', 'Syphilis'), ('gonorrhoea', 'Gonorrhoea'), ('hpv', 'HPV'), ('hsv2', 'HSV-2'), ('none', 'None / Indeterminate')], db_index=True, max_length=20)),
                ('forecast_generated_on', models.DateField()),
                ('baseline_start', models.DateField()),
                ('baseline_end', models.DateField()),
                ('baseline_incidence_rate', models.FloatField(help_text='Incidence rate per 100,000 in the baseline period')),
                ('forecast_30d_rate', models.FloatField()),
                ('forecast_30d_lower', models.FloatField(help_text='95% CI lower')),
                ('forecast_30d_upper', models.FloatField(help_text='95% CI upper')),
                ('forecast_60d_rate', models.FloatField()),
                ('forecast_60d_lower', models.FloatField()),
                ('forecast_60d_upper', models.FloatField()),
                ('forecast_90d_rate', models.FloatField()),
                ('forecast_90d_lower', models.FloatField()),
                ('forecast_90d_upper', models.FloatField()),
                ('year_over_year_delta_pct', models.FloatField(help_text='% change vs same period last year. Positive = worsening trend.', null=True)),
                ('trend_direction', models.CharField(choices=[('rising', 'Rising'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', max_length=20)),
                ('lstm_mape', models.FloatField(help_text='LSTM walk-forward MAPE on validation set', null=True)),
                ('prophet_mape', models.FloatField(null=True)),
                ('ensemble_weight_lstm', models.FloatField(default=0.6)),
                ('ensemble_weight_prophet', models.FloatField(default=0.4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbreak_forecasts', to='ml_pipeline.mlmodel')),
            ],
            options={
                'ordering': ['-forecast_generated_on'],
                'indexes': [models.Index(fields=['county', 'sti_type'], name='ml_pipeline_county_5f9520_idx'), models.Index(fields=['forecast_generated_on'], name='ml_pipeline_forecas_5620f9_idx')],
                'unique_together': {('county', 'sti_type', 'forecast_generated_on')},
            },
        ),
        migrations.AddIndex(
            model_name='riskprediction',
            index=models.Index(fields=['anonymous_id', 'created_at'], name='ml_pipeline_anonymo_02315b_idx'),
        ),
        migrations.AddIndex(
            model_name='riskprediction',
            index=models.Index(fields=['overall_risk_level'], name='ml_pipeline_overall_b4e454_idx'),
        ),
        migrations.AddIndex(
            model_name='riskprediction',
            index=models.Index(fields=['clinical_review_required', 'clinical_review_completed'], name='ml_pipeline_clinica_b28705_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionauditlog',
            index=models.Index(fields=['event_type', 'timestamp'], name='ml_pipeline_event_t_3ab80e_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionauditlog',
            index=models.Index(fields=['anonymous_id'], name='ml_pipeline_anonymo_bdaba0_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingjob',
            index=models.Index(fields=['model_type', 'status'], name='ml_pipeline_model_t_0e2eec_idx'),
        ),
    ]
