# Generated by Django 6.0.3 on 2026-07-13 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(db_index=True, max_length=50)),
                ('model_type', models.CharField(choices=[('logistic_regression', 'Logistic Regression'), ('random_forest', 'Random Forest'), ('xgboost', 'XGBoost'), ('lightgbm', 'LightGBM'), ('neural_network', 'Neural Network'), ('svm', 'Support Vector Machine')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('model_file', models.FileField(upload_to='models/%Y/%m/%d/')),
                ('scaler_file', models.FileField(blank=True, null=True, upload_to='models/%Y/%m/%d/')),
                ('metadata_file', models.FileField(blank=True, null=True, upload_to='models/%Y/%m/%d/')),
                ('hyperparameters', models.JSONField(blank=True, default=dict)),
                ('training_accuracy', models.FloatField(blank=True, null=True)),
                ('validation_accuracy', models.FloatField(blank=True, null=True)),
                ('test_auc_roc', models.FloatField(blank=True, null=True)),
                ('test_f1', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('training', 'Training'), ('ready', 'Ready for Deployment'), ('deployed', 'Deployed'), ('deprecated', 'Deprecated'), ('failed', 'Failed')], default='training', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('training_data_size', models.PositiveIntegerField(blank=True, null=True)),
                ('training_started_at', models.DateTimeField(blank=True, null=True)),
                ('training_completed_at', models.DateTimeField(blank=True, null=True)),
                ('training_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('dataset_path', models.CharField(blank=True, max_length=500)),
                ('test_size', models.FloatField(default=0.2)),
                ('random_state', models.IntegerField(default=42)),
                ('cross_validation_folds', models.PositiveIntegerField(default=5)),
                ('current_epoch', models.PositiveIntegerField(default=0)),
                ('total_epochs', models.PositiveIntegerField(default=100)),
                ('current_fold', models.PositiveIntegerField(default=0)),
                ('logs', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='ml_pipeline.mlmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
