# Generated by Django 6.0.6 on 2026-08-28 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prediction_engine', '0002_riskprediction_likely_stis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('what_this_means', models.TextField()),
                ('important_considerations', models.JSONField(default=list)),
                ('recommended_next_steps', models.JSONField(default=list)),
                ('provider', models.CharField(max_length=50)),
                ('model_identifier', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prediction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_explanation', to='prediction_engine.riskprediction')),
            ],
            options={
                'verbose_name': 'AI prediction explanation',
                'verbose_name_plural': 'AI prediction explanations',
                'ordering': ['-created_at'],
            },
        ),
    ]
