# Generated by Django 6.0.6 on 2026-08-29 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('who', 'World Health Organization'), ('cdc', 'US Centers for Disease Control and Prevention'), ('moh_kenya', 'Kenya Ministry of Health'), ('other', 'Other')], default='other', max_length=30)),
                ('document_type', models.CharField(choices=[('guideline', 'Clinical Guideline'), ('fact_sheet', 'Fact Sheet'), ('patient_info', 'Patient Information'), ('policy', 'Policy Document'), ('other', 'Other')], default='guideline', max_length=30)),
                ('file', models.FileField(upload_to='knowledge/%Y/%m/')),
                ('citation', models.CharField(blank=True, max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('ingested_at', models.DateTimeField(blank=True, null=True)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'knowledge document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('chunk_text', models.TextField()),
                ('embedding_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_service.knowledgedocument')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
                'indexes': [models.Index(fields=['document', 'chunk_index'], name='ai_service__documen_b08ecb_idx')],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
