# Generated by Django 6.0.3 on 2026-06-01 09:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicianProfile',
            fields=[
                ('clinician_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('gp', 'General Practitioner'), ('ids', 'Infectious Disease Specialist'), ('pho', 'Public Health Officer'), ('lab', 'Laboratory Technician'), ('moh', 'MOH Administrator')], max_length=20)),
                ('license_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('license_issuing_body', models.CharField(max_length=100)),
                ('license_expiry_date', models.DateField()),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('suspended', 'Suspended'), ('expired', 'License Expired')], default='pending', max_length=20)),
                ('verified_by', models.CharField(blank=True, max_length=100)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('facility_name', models.CharField(max_length=200)),
                ('facility_county', models.CharField(max_length=50)),
                ('facility_sub_county', models.CharField(max_length=50)),
                ('can_view_patient_risk', models.BooleanField(default=True)),
                ('can_view_population_data', models.BooleanField(default=False)),
                ('can_approve_guidance', models.BooleanField(default=False)),
                ('can_override_threshold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinician_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('prediction_viewed', 'Prediction Viewed'), ('guidance_accessed', 'Guidance Accessed'), ('alert_acknowledged', 'Alert Acknowledged'), ('alert_resolved', 'Alert Resolved'), ('threshold_override', 'Threshold Override'), ('patient_referred', 'Patient Referred'), ('test_ordered', 'Test Ordered'), ('guidance_approved', 'Guidance Approved'), ('guidance_deployed', 'Guidance Deployed')], max_length=50)),
                ('anonymous_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('risk_score', models.FloatField(null=True)),
                ('guidance_version', models.PositiveIntegerField(null=True)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('clinician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicians.clinicianprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PatientRiskAlert',
            fields=[
                ('alert_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_id', models.CharField(db_index=True, max_length=64)),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
                ('sti_probabilities', models.JSONField(default=dict)),
                ('top_features', models.JSONField(default=list, help_text='Top 3 contributing features (SHAP)')),
                ('facility_county', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('under_review', 'Under Review'), ('reviewed', 'Reviewed'), ('escalated', 'Escalated'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('clinician_notes', models.TextField(blank=True)),
                ('recommended_action', models.CharField(blank=True, max_length=50)),
                ('test_orders', models.JSONField(blank=True, default=list)),
                ('referral_made', models.BooleanField(default=False)),
                ('referral_destination', models.CharField(blank=True, max_length=200)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_clinician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to='clinicians.clinicianprofile')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='PopulationRiskSummary',
            fields=[
                ('summary_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facility_county', models.CharField(max_length=50)),
                ('facility_sub_county', models.CharField(blank=True, max_length=50)),
                ('reporting_period_start', models.DateField()),
                ('reporting_period_end', models.DateField()),
                ('total_patients_assessed', models.PositiveIntegerField(default=0)),
                ('low_risk_count', models.PositiveIntegerField(default=0)),
                ('moderate_risk_count', models.PositiveIntegerField(default=0)),
                ('high_risk_count', models.PositiveIntegerField(default=0)),
                ('critical_risk_count', models.PositiveIntegerField(default=0)),
                ('sti_distribution', models.JSONField(default=dict, help_text='Counts per STI type')),
                ('new_alerts_this_period', models.PositiveIntegerField(default=0)),
                ('resolved_alerts_this_period', models.PositiveIntegerField(default=0)),
                ('avg_time_to_acknowledgment_hours', models.FloatField(null=True)),
                ('week_over_week_delta', models.FloatField(help_text='Percentage change in critical alerts', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reporting_period_end'],
                'unique_together': {('facility_county', 'facility_sub_county', 'reporting_period_end')},
            },
        ),
        migrations.CreateModel(
            name='ClinicalGuidance',
            fields=[
                ('guidance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('sti_type', models.CharField(choices=[('hiv', 'HIV'), ('chlamydia', 'Chlamydia'), ('syphilis', 'Syphilis'), ('gonorrhoea', 'Gonorrhoea'), ('hpv', 'HPV'), ('hsv2', 'HSV-2'), ('general', 'General STI Guidance')], max_length=20)),
                ('symptom_pattern', models.JSONField(default=dict, help_text='Symptom combinations triggering this guidance')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('differential_diagnosis', models.JSONField(default=list, help_text='Ranked differential diagnoses')),
                ('recommended_tests', models.JSONField(default=list)),
                ('treatment_protocol', models.JSONField(default=dict, help_text='MOH-aligned treatment protocol')),
                ('referral_criteria', models.JSONField(default=list)),
                ('patient_counseling_points', models.JSONField(default=list)),
                ('drafted_by', models.CharField(max_length=100)),
                ('reviewed_by_clinician_1', models.CharField(blank=True, max_length=100)),
                ('reviewed_by_clinician_2', models.CharField(blank=True, max_length=100)),
                ('infectious_disease_specialist', models.CharField(blank=True, max_length=100)),
                ('moh_signatory', models.CharField(blank=True, max_length=100)),
                ('validation_status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('clinician_approved', 'Clinician Approved'), ('moh_approved', 'MOH Approved'), ('deployed', 'Deployed'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('annual_review_due', models.DateField(blank=True, null=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicians.clinicalguidance')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sti_type', 'risk_level', 'validation_status'], name='clinicians__sti_typ_d2ff04_idx'), models.Index(fields=['version', 'validation_status'], name='clinicians__version_2230ae_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='clinicianprofile',
            index=models.Index(fields=['license_number', 'verification_status'], name='clinicians__license_967d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicianprofile',
            index=models.Index(fields=['facility_county', 'role'], name='clinicians__facilit_75c5ca_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['clinician', 'action_type'], name='clinicians__clinici_3d55ee_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['anonymous_id', 'timestamp'], name='clinicians__anonymo_52b0a2_idx'),
        ),
        migrations.AddIndex(
            model_name='patientriskalert',
            index=models.Index(fields=['status', 'facility_county'], name='clinicians__status_e17791_idx'),
        ),
        migrations.AddIndex(
            model_name='patientriskalert',
            index=models.Index(fields=['anonymous_id', 'triggered_at'], name='clinicians__anonymo_a0651d_idx'),
        ),
        migrations.AddIndex(
            model_name='patientriskalert',
            index=models.Index(fields=['assigned_clinician', 'status'], name='clinicians__assigne_a34870_idx'),
        ),
    ]
