"""
Orchestrates AI explanation generation.

The flow is deliberately one-directional:

    RiskPrediction (already computed and persisted by prediction_engine)
        -> context_builder      de-identify and flatten
        -> retrieval            grounding documents (empty in Phase 1)
        -> prompts              system + user message
        -> providers            constrained JSON generation
        -> validation           enforce shape, override disclaimer
        -> PredictionExplanation (persisted)

No prediction logic is performed or duplicated here. This module never
imports STIPredictor, never touches a feature vector, and cannot change a
risk score -- it only reads fields off a stored row.
"""

import logging
from typing import Dict, List, Optional, Tuple

from . import prompts, retrieval, safety
from .config import AISettings, get_ai_settings
from .context_builder import build_explanation_context
from .models import PredictionExplanation
from .providers import LLMResponseError, get_provider
from .schemas import EXPLANATION_JSON_SCHEMA

logger = logging.getLogger(__name__)

#: Fields the provider must return, mirroring EXPLANATION_JSON_SCHEMA.
_REQUIRED_TEXT_FIELDS = ('summary', 'what_this_means')
_REQUIRED_LIST_FIELDS = ('important_considerations', 'recommended_next_steps')


def _clean_string_list(value, field_name: str) -> List[str]:
    """Validate a list-of-strings field, discarding blanks."""
    if not isinstance(value, list):
        raise LLMResponseError(f'Expected a list for {field_name!r}.')

    cleaned = [str(item).strip() for item in value if str(item).strip()]
    if not cleaned:
        raise LLMResponseError(f'Field {field_name!r} was empty.')
    return cleaned


def validate_explanation_payload(payload: Dict) -> Dict:
    """
    Check a provider response before it is stored or shown.

    Structured outputs make a malformed response unlikely, but "unlikely" is
    not a guarantee to build a clinical UI on -- a provider outage, a proxy or
    a future provider without schema support could all return something else.
    Anything unexpected raises LLMResponseError, which the caller turns into
    the graceful-degradation path.
    """
    if not isinstance(payload, dict):
        raise LLMResponseError('Expected a JSON object from the provider.')

    result = {}

    for field in _REQUIRED_TEXT_FIELDS:
        value = payload.get(field)
        if not isinstance(value, str) or not value.strip():
            raise LLMResponseError(f'Missing or empty field {field!r}.')
        result[field] = value.strip()

    for field in _REQUIRED_LIST_FIELDS:
        result[field] = _clean_string_list(payload.get(field), field)

    return result


def serialize_explanation(
    explanation: PredictionExplanation,
    cached: bool,
) -> Dict:
    """
    Render a stored explanation into the API response shape.

    The disclaimer is injected here from prompts.DISCLAIMER_TEXT rather than
    read from storage, so it is authoritative on every response and cannot
    drift even for explanations generated by an earlier version.
    """
    return {
        'available': True,
        'prediction_id': explanation.prediction_id,
        'summary': explanation.summary,
        'what_this_means': explanation.what_this_means,
        'important_considerations': list(explanation.important_considerations or []),
        'recommended_next_steps': list(explanation.recommended_next_steps or []),
        'disclaimer': prompts.DISCLAIMER_TEXT,
        'generated_by': {
            'provider': explanation.provider,
            'model': explanation.model_identifier,
        },
        'cached': cached,
        'generated_at': explanation.created_at,
    }


def get_cached_explanation(prediction) -> Optional[PredictionExplanation]:
    """Return the stored explanation for a prediction, or None."""
    return PredictionExplanation.objects.filter(prediction=prediction).first()


def _screen(payload: Dict, context: Dict, documents: List[Dict]) -> List[Dict]:
    """
    Run every safety screen over a generated explanation.

    Two screens with different inputs: screen_explanation() judges the prose
    on its own (diagnosis, certainty, alarmism, duplication), while
    screen_grounding() judges it against what the model was actually given
    (invented statistics, fabricated citations, treatment advice,
    contradictions of the risk level). Combining them here means the retry
    path handles both identically and callers cannot forget one.
    """
    return (
        safety.screen_explanation(payload)
        + safety.screen_grounding(payload, context, documents)
    )


def generate_explanation(
    prediction,
    ai_settings: AISettings = None,
) -> Tuple[PredictionExplanation, Dict]:
    """
    Call the provider and persist the result.

    Raises LLMError (or a subclass) on any failure. Callers are expected to
    catch it -- a failure here must never propagate as a 500, because the
    prediction itself is perfectly valid.
    """
    ai_settings = ai_settings or get_ai_settings()

    # Raises LLMNotConfiguredError when disabled, keyless or misconfigured.
    provider = get_provider(ai_settings)

    context = build_explanation_context(prediction)

    # Grounding passages from the knowledge base, or none.
    #
    # Guarded even though ChromaRetriever already swallows its own failures:
    # a Retriever is an interface anyone can implement, and a buggy one must
    # not be able to turn a working explanation into a 500. Grounding is an
    # enhancement, so its worst case is an ungrounded explanation -- the same
    # supported path taken when no knowledge base exists at all.
    try:
        from django.conf import settings

        retriever = retrieval.get_retriever()
        documents = retriever.retrieve(
            retrieval.build_retrieval_query(context),
            # Each injected passage lengthens the prompt, and on a local CPU
            # model prompt length costs real generation time -- roughly a
            # doubling between none and four passages. RAG_TOP_K is the lever
            # for that tradeoff.
            limit=getattr(settings, 'RAG_TOP_K', 4),
        )
    except Exception:  # noqa: BLE001 - never let retrieval break generation
        logger.exception(
            'Retriever failed for prediction %s; continuing without grounding',
            prediction.pk,
        )
        documents = []

    user_prompt = prompts.build_user_prompt(context, context_documents=documents)
    request_id = f'prediction-{prediction.pk}'

    payload = provider.generate_json(
        system_prompt=prompts.SYSTEM_PROMPT,
        user_prompt=user_prompt,
        json_schema=EXPLANATION_JSON_SCHEMA,
        request_id=request_id,
    )
    validated = validate_explanation_payload(payload)

    # Post-generation safety screen. The schema stops the model returning a
    # diagnosis *field*; it cannot stop one being written into prose, and
    # small local models do exactly that. On a violation, retry once naming
    # the offending phrase -- far more effective on a weak model than
    # repeating the rule it already ignored.
    violations = _screen(validated, context, documents)
    if violations:
        logger.warning(
            'Safety screen rejected explanation for prediction %s: %s',
            prediction.pk,
            '; '.join(f"{v['field']}: {v['match']!r} ({v['reason']})" for v in violations),
        )

        retry_payload = provider.generate_json(
            system_prompt=prompts.SYSTEM_PROMPT,
            user_prompt=user_prompt + safety.build_correction_note(violations),
            json_schema=EXPLANATION_JSON_SCHEMA,
            request_id=f'{request_id}-safety-retry',
        )
        validated = validate_explanation_payload(retry_payload)

        violations = _screen(validated, context, documents)
        if violations:
            # Two failures means this model cannot follow the rules for this
            # input. Showing unsafe text to a patient is worse than showing
            # none, so degrade to the "unavailable" path instead.
            logger.error(
                'Safety screen rejected the retry for prediction %s; '
                'no explanation will be shown.',
                prediction.pk,
            )
            raise LLMResponseError(
                'The generated explanation did not meet safety requirements.'
            )

    explanation, _ = PredictionExplanation.objects.update_or_create(
        prediction=prediction,
        defaults={
            **validated,
            'provider': provider.name,
            'model_identifier': provider.model,
        },
    )

    logger.info(
        'Generated AI explanation for prediction %s using %s/%s',
        prediction.pk, provider.name, provider.model,
    )

    return explanation, serialize_explanation(explanation, cached=False)


def explain_prediction(prediction, refresh: bool = False) -> Dict:
    """
    Main entry point used by the API layer.

    Returns the stored explanation when one exists and `refresh` is False,
    otherwise generates a new one.
    """
    if not refresh:
        cached = get_cached_explanation(prediction)
        if cached is not None:
            return serialize_explanation(cached, cached=True)

    _, response = generate_explanation(prediction)
    return response
