# Generated by Django 6.0.3 on 2026-05-26 21:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Assessment Completed'), ('expired', 'Session Expired'), ('converted', 'Tested at Clinic')], default='active', max_length=20)),
                ('consent_testing_reminder', models.BooleanField(default=False)),
                ('consent_result_tracking', models.BooleanField(default=False)),
                ('county', models.CharField(blank=True, db_index=True, max_length=50)),
                ('sub_county', models.CharField(blank=True, max_length=50)),
                ('device_hash', models.CharField(blank=True, help_text='Hashed device fingerprint for rate limiting', max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expires_at'], name='patients_an_status_3ca89b_idx'), models.Index(fields=['device_hash', 'created_at'], name='patients_an_device__9e0ddf_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientAssessment',
            fields=[
                ('assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptoms_reported', models.JSONField(default=dict, help_text='32 symptom responses')),
                ('behaviours_reported', models.JSONField(default=dict)),
                ('demographics_reported', models.JSONField(default=dict)),
                ('risk_score', models.FloatField(null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('sti_probabilities', models.JSONField(default=dict)),
                ('top_contributing_factors', models.JSONField(default=list)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('follow_up_scheduled', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='patients.anonymoussession')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientEducationContent',
            fields=[
                ('content_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('plain_language_summary', models.TextField()),
                ('what_to_do_next', models.JSONField(default=list)),
                ('when_to_seek_care', models.TextField()),
                ('prevention_tips', models.JSONField(default=list)),
                ('myth_busters', models.JSONField(default=list)),
                ('validated_by', models.CharField(max_length=100)),
                ('validated_at', models.DateTimeField()),
                ('review_due', models.DateField()),
                ('language', models.CharField(default='en', max_length=10)),
            ],
            options={
                'unique_together': {('risk_level', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ResultTracking',
            fields=[
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_date', models.DateField()),
                ('test_type', models.CharField(max_length=50)),
                ('self_reported_result', models.CharField(choices=[('negative', 'Negative'), ('positive', 'Positive'), ('inconclusive', 'Inconclusive'), ('pending', 'Pending')], max_length=20)),
                ('previous_risk_score', models.FloatField(null=True)),
                ('current_risk_score', models.FloatField(null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='patients.anonymoussession')),
            ],
        ),
        migrations.CreateModel(
            name='TestingReminder',
            fields=[
                ('reminder_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('reminder_type', models.CharField(choices=[('3_day', '3 Day Follow-up'), ('1_week', '1 Week Follow-up'), ('2_week', '2 Week Follow-up'), ('1_month', '1 Month Follow-up'), ('3_month', '3 Month Follow-up')], max_length=20)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='patients.anonymoussession')),
            ],
        ),
    ]
