# Generated by Django 6.0.3 on 2026-07-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=1)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_county', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('cohabiting', 'Cohabiting')], default='single', max_length=20)),
                ('number_of_partners_12m', models.IntegerField(default=0)),
                ('number_of_partners_lifetime', models.IntegerField(default=0)),
                ('condom_use_frequency', models.FloatField(default=0.0)),
                ('substance_use', models.BooleanField(default=False)),
                ('substance_type', models.CharField(blank=True, max_length=255, null=True)),
                ('prior_sti_history', models.BooleanField(default=False)),
                ('prior_sti_types', models.CharField(blank=True, max_length=255, null=True)),
                ('hiv_status_known', models.BooleanField(default=False)),
                ('hiv_status', models.CharField(choices=[('unknown', 'Unknown'), ('negative', 'Negative'), ('positive', 'Positive')], default='unknown', max_length=20)),
                ('symptoms_present', models.BooleanField(default=False)),
                ('symptom_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
